---
title: "Scraping US-Mexico results from WIkipedia"
author: "Joseph Kroymann"
date: "6/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
# installing necessary packages
if (!require(pacman)) {
  install.packages("pacman")
}

pacman::p_load(tidyverse, rvest, stringr)

# loading necessary packages
library(tidyverse)
library(rvest)
library(stringr)
```

```{r, echo=FALSE}
# setting url of website to be scraped + reading in html code
url <- "https://en.wikipedia.org/wiki/Mexico%E2%80%93United_States_soccer_rivalry#List_of_Matches_2"
webpage <- read_html(url)

# extracting game list from wikipedia url
games <- webpage %>%
  html_nodes(xpath = '/html/body/div[3]/div[3]/div[5]/div[1]/table[7]') %>%
  html_table() 

# extracting df from list + adding friendly indicator, goals scored for us and mexico each game
games <- games[[1]][c(1:71),] 

games <- games %>%
  mutate(Friendly = Competition == "Friendly", 
         US = c(4,2,3,1,0,0,2,0,1,0,2,3,0,2,0,1,1,0,1,0,0,0,0,0,1,2,
                1,2,2,0,1,1,4,0,2,0,2,0,0,1,1,3,2,2,0,1,2,0,1,1,2,2,
                2,2,2,0,1,2,1,1,0,2,2,2,2,1,1,1,0,0,3),
         Mexico = c(2,7,7,5,5,6,6,4,3,6,7,3,3,2,2,3,2,2,3,1,2,0,3,3,  
                    5,1,2,2,0,4,1,0,0,0,2,2,2,0,1,2,1,0,0,0,1,0,0,0,
                    0,2,0,0,1,2,0,5,2,4,1,0,0,0,2,0,2,2,1,0,1,3,2),
         ResIndicator = case_when(
           US > Mexico ~ 1,
           US == Mexico ~ 0,
           US < Mexico ~ -1),
         Game_Num = 1:71,
         Date = str_sub(Date, -4))
```

```{r, echo=FALSE, fig.height= 1.5, fig.width=10}
# visualization - goal difference of each game
colors <- c("#006341", "#FFFFFF", "#B22234")

games %>%
  ggplot(aes(x = 1:nrow(games), y = ResIndicator, shape = Friendly)) +
  scale_shape_manual(values = c(1, 19),
                     breaks = c("FALSE", "TRUE"),
                     labels = c("Competitive", "Friendly")) +
  geom_segment(aes(x = Game_Num, xend = Game_Num, y = 0, yend = ResIndicator), 
               size = 1, color = factor(ifelse(games$ResIndicator > 0, "#3C3B6E", "#006341"))) +
  geom_point(color = factor(case_when(
    games$ResIndicator > 0 ~ "#B22234",
    games$ResIndicator == 0 ~ "white",
    games$ResIndicator < 1 ~ "#CE1126")),
    size = 3) +
  ylim(-1.3, 1.3) +
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        plot.title = element_text(color = "white"),
        plot.caption = element_text(color = "white", hjust = 1.15),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "black", colour = "white"),
        plot.background = element_rect(fill = "black", colour = "black"),
        legend.background = element_rect(fill = "black", colour = "white"),
        legend.title = element_blank(),
        legend.text = element_text(color = "white")) +
  labs(title = "USA-Mexico All-Time Results Map (1934-2021)",
       caption = "Data Source: Wikipedia")
        
```



